### ISSUE TITLE
Improve footnotes calls styling

### ISSUE THREAD

**Issue by robindemourat** [peritext/ovide#76]
They are too large.

Possible fix: 

```css
.content sup{
  max-width: 1rem;
  display: inline-block;
}
```
